[package]
name = "game-rust"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]
edition = "2018"

[dependencies]
wgpu = "0.5.0"
wgpu_glyph = "0.8.0"
winit = "0.22.1"
futures = "0.3.5"
env_logger = "0.7.1"
vk-shader-macros = "0.2.2"
nalgebra = "0.21.0"
bytemuck = "1.2.0"
